dist: trusty
sudo: false
language: go
go:
  - "1.10"
  - "1.11"
env:
  global:
    - PATH=$PATH:$HOME/gopath/bin
before_install:
  - echo "machine github.com login $BUNDLE_GITHUB__COM" > $HOME/.netrc
  - echo "machine raw.githubusercontent.com login $BUNDLE_GITHUB__COM" >> $HOME/.netrc
  - chmod 600 $HOME/.netrc
install:
  - go get -u github.com/golang/dep/cmd/dep
  - dep ensure -v
script:
  - go test -v
  - curl -n -s https://raw.githubusercontent.com/gtforge/gett_tools_scripts/master/code_analysis/golang/travis-check/golangci.sh | bash
