# Refer to https://golang.github.io/dep/docs/Gopkg.toml.html
# for detailed Gopkg.toml documentation.

[[constraint]]
  name = "github.com/astaxie/beego"
  version = ">1.9.2"

[[constraint]]
  name = "github.com/newrelic/go-agent"
  version = ">=1.11.0"

[prune]
  go-tests = true
  unused-packages = true
